version: "4.1.1"
services:
  redis:
     image: "redis:alpine"
     hostname: redis
     ports:
       - 6379:6379
  web:
    image: ecom-api
    build:
      context: .
    container_name: book-app
    # depends_on:
    #   - redis
    ports:
      - 8081:8081
    volumes:
      - .:/app
    command: bash -c "go build -o book-app . && ./book-app"
