version: "4.1.1"
services: 
    web:
        build:
            context: .
        image: book-app
        ports: 
            - "8081:8081"
        volumes: 
            - .:/app/
        command: bash -c "go get github.com/pilu/fresh && fresh"
